---

- name: Get Subscription Status
  command:
    cmd: 'subscription-manager list --consumed --matches {{ rhsm_sku }}'
  failed_when: false #  rocky linux does not include subscription-manager
  check_mode: false
  changed_when: false
  register: rhsm_status

- name: Set Subscription Status
  set_fact:
    rhsm_subscribed: '{{ rhsm_status.stdout | default( "Active: False" ) 
      | regex_search("Active:.*") | regex_replace("Active: *", "")|bool() }}'

- block:
  - name: Ensure Red Hat Insights Client is installed
    yum:
      name: "{{ insights_packagename }}"
      state: present

  - name: Register to the Red Hat Insights Service
    command:
      cmd: "{{ insights_clientname }} --register"
      creates: "{{ insights_client_conf_dir }}/.registered"
    when: rhsm_subscribed
