---

- name: Collect ansible facts
  setup:
    gather_subset: "all"

- block:
  - name: Ensure Red Hat Insights Client is installed
    yum:
      name: "{{ insights_packagename }}"
      state: present

  - name: Register to the Red Hat Insights Service
    command: >
      {{ insights_clientname }} --register
    args:
      creates: "{{ insights_client_conf_dir }}/.registered"
  when: ansible_distribution == "RedHat" and
        (ansible_local.subscription_custom_rhel.rhn_subscriptions_consumed.subscription_1_name == "Red_Hat_Enterprise_Linux_for_Virtual_Datacenters_Standard" or ansible_local.subscription_custom_rhel.rhn_subscriptions_consumed.subscription_1_name == "Red_Hat_Enterprise_Linux_Server_Standard_(Physical_or_Virtual_Nodes)" ) and ansible_local.subscription_custom_rhel.rhn_subscriptions_consumed.subscription_1_active == "True"
